- cmd/main.go
- pkg/provenance/logs.go
Modified to use inbuilt github env variables to obtain run ID to query instead.
Left `GetBuildLogsURL` alone since it is currently unused. 
Signed-off-by: Brandon Lum <lumjjb@gmail.com>
> Fix race when running multiple concurrent workload runs

- builder-golang/action.yaml
builder-golang/action.yaml: Define the action
Add golang builder action
Tested using this file https://github.com/laurentsimon/slsa-on-github-test/blob/main/.github/workflows/builder-test.yaml
> Add golang builder action

- .github/workflows/integration.yml
- slsa-provenance/action.yml
- slsa-provenance/generator/cmd/main.go
- slsa-provenance/generator/go.mod
Signed-off-by: Asra Ali <asraa@google.com>
> fix test workflow

- slsa-provenance/action.yml
Signed-off-by: Asra Ali <asraa@google.com>
> Fix: Use input variable for downloading binary

- .github/workflows/slsa-builder-go.yml
- build-go/pkg/build.go
> ✨ Separate builder's build and project's build

- .github/workflows/slsa-builder-go.yml
- build-go/main.go
- build-go/pkg/build.go
See title
closes https://github.com/asraa/slsa-on-github/issues/25
> ✨ use allow list for env variables and arguments

- .github/workflows/slsa-builder-go.yml
- build-go/main.go
- build-go/pkg/build.go
- build-go/pkg/config.go
Note: merge https://github.com/asraa/slsa-on-github/pull/27 before.
closes https://github.com/asraa/slsa-on-github/issues/26
> ✨ Flexible binary name

- .github/workflows/slsa-builder-go.yml
- build-go/main.go
- build-go/pkg/build.go
- build-go/pkg/build_test.go
- build-go/pkg/config.go
see title
No: need to be rebased when previous PRs are merged
> Unit tests for arg/env filtering

- .github/workflows/slsa-builder-go.yml
- build-go/go.mod
- build-go/go.sum
- build-go/main.go
- build-go/pkg/build.go
- build-go/pkg/build_test.go
- build-go/pkg/config.go
- build-go/pkg/testdata/releaser-invalid-envs.yml
- build-go/pkg/testdata/releaser-invalid-version.yml
- build-go/pkg/testdata/releaser-noversion.yml
- build-go/pkg/testdata/releaser-valid.yml
see title.
Note: need previous PRs merged.
> ✨ Unit tests for config

- build-go/pkg/config_test.go
> 🐛 Missing file in previous PR

- build-go/pkg/build_test.go
> ✨ Unit tests for generateFlags

- build-go/pkg/build.go
- build-go/pkg/build_test.go
> ✨ Unit tests for generateLdflags

- .github/workflows/pre-submit.yml
> 🐛 Fix workflow indentation

- build-go/pkg/build.go
- build-go/pkg/build_test.go
> ✨ Unit test for generateFlags

- .github/workflows/pre-submit.yml
- provenance-verifier/pkg/testdata/workflow-job-env-empty.yml
- provenance-verifier/pkg/testdata/workflow-job-env-mix.yml
- provenance-verifier/pkg/testdata/workflow-job-env-one-set-single.yml
- provenance-verifier/pkg/testdata/workflow-job-env-set.yml
- provenance-verifier/pkg/testdata/workflow-no-job-env.yml
- provenance-verifier/pkg/workflow.go
- provenance-verifier/pkg/workflow_test.go
see title
needs to be rebased when https://github.com/asraa/slsa-on-github/pull/45 is merged.
> ✨ Job level env unit tests for verifier

- .github/workflows/pre-submit.yml
- provenance-verifier/pkg/testdata/workflow-job-env-empty.yml
- provenance-verifier/pkg/testdata/workflow-job-env-mix.yml
- provenance-verifier/pkg/testdata/workflow-job-env-one-set-single.yml
- provenance-verifier/pkg/testdata/workflow-job-env-set.yml
- provenance-verifier/pkg/testdata/workflow-no-job-env.yml
- provenance-verifier/pkg/testdata/workflow-no-top-defaults.yml
- provenance-verifier/pkg/testdata/workflow-top-defaults.yml
- provenance-verifier/pkg/workflow.go
- provenance-verifier/pkg/workflow_test.go
see title
Note: needs https://github.com/asraa/slsa-on-github/pull/46 to be merged.
> ✨ Unit test for top level defaults verifier

- .github/workflows/slsa-builder-go.yml
- build-go/main.go
- build-go/pkg/build.go
see https://github.com/asraa/slsa-on-github/issues/50 and https://github.com/asraa/slsa-on-github/issues/49
> ✨ Separate argument generation and builder

- provenance-verifier/pkg/testdata/workflow-first-self-hosted-runners.yml
- provenance-verifier/pkg/testdata/workflow-gh-hosted-runners.yml
- provenance-verifier/pkg/testdata/workflow-no-runner.yml
- provenance-verifier/pkg/testdata/workflow-second-self-hosted-runners.yml
- provenance-verifier/pkg/testdata/workflow-third-self-hosted-runners.yml
- provenance-verifier/pkg/workflow.go
- provenance-verifier/pkg/workflow_test.go
> ✨ Unit tests for self-hosted runners

- provenance-verifier/pkg/testdata/workflow-first-self-hosted-runners.yml
- provenance-verifier/pkg/testdata/workflow-gh-hosted-runners.yml
- provenance-verifier/pkg/testdata/workflow-job-steps-mix.yml
- provenance-verifier/pkg/testdata/workflow-no-runner.yml
- provenance-verifier/pkg/testdata/workflow-no-steps.yml
- provenance-verifier/pkg/testdata/workflow-second-self-hosted-runners.yml
- provenance-verifier/pkg/testdata/workflow-third-self-hosted-runners.yml
- provenance-verifier/pkg/workflow.go
- provenance-verifier/pkg/workflow_test.go
needs https://github.com/asraa/slsa-on-github/pull/54 merged
> ✨ Unit tests for step declaration

- provenance-verifier/pkg/testdata/workflow-no-reusable-workflow.yml
- provenance-verifier/pkg/testdata/workflow-reusable-workflow-mix.yml
- provenance-verifier/pkg/workflow.go
- provenance-verifier/pkg/workflow_test.go
Note: the actionlinter is pretty strict: if env variables are declared, or runs-on id declared, it will fail.. which plays in our favor
> ✨ Unit tests for re-usable workflow call

- README.md
Temporary link. We'll have the workflow example in the gossts repo
> Link to example

- .github/workflows/slsa-builder-go.yml
closes https://github.com/asraa/slsa-on-github/issues/64
> ✨ Remove upload-location input from the workflow

- .github/workflows/slsa-builder-go.yml
closes https://github.com/asraa/slsa-on-github/issues/63
> ✨ Update config file name
